---

- name: Run apt update & apt safe-upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: safe
    cache_valid_time: 3600

- name: "Check if reboot is required"
  stat:
    path: "/var/run/reboot-required"
  register: result

- name: Reboot if required
  ansible.builtin.reboot:
  when: result.stat.exists
